### ISSUE TITLE
Package build against wrong version of .Net Framework

### ISSUE THREAD

**Issue by deMD** [TruePeople/TruePeople.SharePreview#4]
After installing the preview package I get the following message in my error log:
```
The primary reference "TruePeople.SharePreview, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETFramework,Version=v4.8" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.7.2".
```

As Umbraco is build against version 4.7.2 all packages for Umbraco should be build against the same framework version for compatibility, upgrading the solution to a higher Framework version is not an option for us. Currently this causes issues on out release environments as the package does not work there.

**Comment by joepvtl** [comment]
Hi,

I am going to look into this right now,

**Comment by joepvtl** [comment]
Hey @deMD ,

I have released a alpha version that should fix your issue, can you try installing it and see if it does fix your issue?

https://www.nuget.org/packages/TruePeople.SharePreview/1.0.2-alpha

**Comment by deMD** [comment]
Hi @joepvtl 

Releasing with this package worked 👍

**Comment by joepvtl** [comment]
Will release a non-alpha version in the beginning of next week!

**Comment by agrath** [comment]
FWIW, we target 4.8 for our Umbraco projects and it works fine (with this package too)

**Comment by joepvtl** [comment]
Released new version with a correct target framework.
