### ISSUE TITLE
End preview button isn't working

### ISSUE THREAD

**Issue by agrath** [TruePeople/TruePeople.SharePreview#5]
I have a node which has previously published content, and I've saved some content that changes it, then used the share preview link, which I view in a chrome incognito window. Everything works fine. 
The preview URL has a badge in the top right which has a little power button that has a tooltip - end preview
But the link is just back to the same page. I think this is the Umbraco built in preview badge, but it would be good if this could be hijacked to return to either the / url or the currently published version of the page

![image](https://user-images.githubusercontent.com/78284/100555813-edf2de00-3302-11eb-8a35-f613d54efcf3.png)

**Comment by agrath** [comment]
![image](https://user-images.githubusercontent.com/78284/100555900-5b067380-3303-11eb-8954-4f375ec1fa3f.png)

Looks like the preview badge html comes from umbracosettings, and the URL used for the end button comes from 
Current.UmbracoContext.HttpContext.Request.Path - so not sure if this is going to be possible to override

**Comment by joepvtl** [comment]
Hi @agrath, thanks for reporting this. I think this started since update 1.0.1 when started forcing a temporary preview mode. We had to do this because else content that was chosen with pickers didn't return the latest version of course. I am not to sure if we can workaround this somehow either. I will look into it, but won't promise anything :)

**Comment by joepvtl** [comment]
@agrath what version of Umbraco are you using?

**Comment by agrath** [comment]
@joepvtl the site we're using this plugin on right now is 8.4.0 - we have a bunch of internal libraries & plugins that target 8.4.0 so we haven't jumped up to a later version yet (new sites are 8.9.x i think)
Given the value comes from HttpContext.Request.Path (in the helper, but in the viewbase comes from pathandquery)
I can't see a way to override it. 

A simple solution here is to edit the HTML of the badge in settings to remove the end button I guess, it looks like it won't be possible to override

![image](https://user-images.githubusercontent.com/78284/100661546-7c756700-33b8-11eb-9fdb-3fac2b0a507e.png)

**Comment by joepvtl** [comment]
Hey @agrath ,

I have been looking into this and have found a possible solution. I am going to remove the previewbadge entirely from the html, because the previewbadge has no use in this case.

**Comment by joepvtl** [comment]
I will try to get a new version out this week.

**Comment by joepvtl** [comment]
Hey @agrath, I have released a new version that removes the previewbadge entirely. You can download it via nuget or our.umbraco . Thanks for reporting issues, I really appreciate any feedback 👍

**Comment by agrath** [comment]
@joepvtl  nice one thanks, our project that uses this plugin still has this function in staging/test so i'll pull the latest version of your package into it now so it can go to live with this version. 
Thank you for fixing the issue
