### ISSUE TITLE
Share Preview in Multi Cultural Site Undefined

### ISSUE THREAD

**Issue by dippas** [TruePeople/TruePeople.SharePreview#9]
Hi, I've installed your package in a project I'm working on, using umbraco 8.16.0, and the link returns undefined, something like this:

**localhost**
localhost:54232/undefined

**dev env**
dev.com/undefinded

Any pointers on what can be wrong?

**Comment by joepvtl** [comment]
Hey,

I will look into it this week and will get back to you!


-Joep

**Comment by dippas** [comment]
@joepvtl  Thank you, I'll debug too, If I came up with the problem/solution I'll let you know :)

**Comment by dippas** [comment]
@joepvtl  figured out the issue. in your `multiple-variants-sharepreview-overlay.html` you are expecting `link.Link` to show and also in the `ng-click=copyShareLink(link.Link)`, but you are passing in the object `link` lowercase. Same thing for `link.CultureName` the object comes with `c` lowercase so doesn't show.

I can make a PR if you'd like

**Comment by joepvtl** [comment]
@dippas yeah a PR would be great! Thanks for putting in the time to investigate.

**Comment by dippas** [comment]
@joepvtl  I did the PR ;)

**Comment by joepvtl** [comment]
Thanks! I will test it and create a new release!
